# Generated by Django 6.0.2 on 2026-04-07 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., B.Tech CSE', max_length=100)),
                ('institution', models.CharField(help_text='e.g., Parul University', max_length=200)),
                ('period', models.CharField(help_text='e.g., 2023 - 2026 | 8.0 CGPA', max_length=100)),
                ('outcome', models.TextField(help_text='Supports Markdown')),
            ],
            options={
                'ordering': ['-period'],
            },
        ),
    ]
